# Generated by Django 3.1.4 on 2020-12-08 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('banner', models.CharField(max_length=400)),
                ('singer', models.CharField(max_length=40)),
                ('data', models.DateField()),
                ('status', models.BooleanField(default='False')),
            ],
        ),
    ]
