# Generated by Django 3.1.4 on 2020-12-08 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='data',
            new_name='date',
        ),
    ]
