# Generated by Django 3.1.4 on 2020-12-13 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0002_albumdata_ststus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Songs_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('artist', models.CharField(max_length=30)),
            ],
        ),
    ]
