# Generated by Django 3.1.4 on 2020-12-13 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0003_songs_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='songs_list',
            name='album',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='album.albumdata'),
        ),
    ]
