# Generated by Django 3.1.4 on 2020-12-13 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0004_songs_list_album'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albumdata',
            name='banner',
            field=models.FileField(upload_to='Banner'),
        ),
    ]
