# Generated by Django 3.1.4 on 2020-12-07 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songs',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
